-- CreateEnum
CREATE TYPE "EntityType" AS ENUM ('Users', 'Contributions', 'Companies', 'ComplaintUpVotes', 'Complaint', 'Reports', 'Subscribers');

-- CreateEnum
CREATE TYPE "ActivityAction" AS ENUM ('LOGIN', 'LOGOUT', 'CREATE_COMPANIES', 'UPDATE_COMPANIES', 'DELETE_COMPANIES', 'CREATE_COMPLAINT', 'UPDATE_COMPLAINT', 'DELETE_COMPLAINT', 'CREATE_COMPLAINTUPVOTES', 'DELETE_COMPLAINTUPVOTES', 'CREATE_REPORTS', 'UPDATE_REPORTS', 'DELETE_REPORTS', 'CREATE_SUBSCRIBERS', 'DELETE_SUBSCRIBERS', 'CREATE_CONTRIBUTIONS', 'UPDATE_CONTRIBUTIONS_ADMIN_ACCEPT', 'UPDATE_CONTRIBUTIONS_ADMIN_UPDATE', 'UPDATE_USER_DETAILS', 'UPDATE_USER_ADMIN_DETAILS', 'CHANGE_PASSWORD');

-- CreateTable
CREATE TABLE "ActivityLog" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "action" "ActivityAction" NOT NULL,
    "entityType" "EntityType" NOT NULL,
    "entityId" TEXT NOT NULL,
    "metadata" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ActivityLog_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ActivityLog" ADD CONSTRAINT "ActivityLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
