-- CreateEnum
CREATE TYPE "Municipality" AS ENUM ('DECAN', 'DRAGASH', 'FERIZAJ', 'FUSHE_KOSOVE', 'GJAKOVE', 'GJILAN', 'GLLOGOC', 'GRACANICE', 'HANI_I_ELEZIT', 'ISTOG', 'JUNIK', 'KACANIK', 'KAMENICE', 'KLINA', 'KLOKOT', 'LEPOSAVIQ', 'LIPJAN', 'MALISHEVE', 'MITROVICE_JUG', 'MITROVICE_VERI', 'NOVO_BRDO', 'OBILIQ', 'PARTESH', 'PEJE', 'PODUJEVE', 'PRISHTINE', 'PRIZREN', 'RAHOVEC', 'RANILLUG', 'SHTERPCE', 'SKENDERAJ', 'SUHAREKE', 'SHARR', 'VITI', 'VUSHTRRI', 'ZUBIN_POTOK', 'ZVECAN');

-- AlterTable
ALTER TABLE "Complaint" ADD COLUMN     "municipality" "Municipality" NOT NULL DEFAULT 'PRISHTINE';
