/*
  Warnings:

  - The values [WORKPLACE_HARASSMENT,WORKPLACE_DISCRIMINATION,WORKPLACE_SAFETY,WORKPLACE_ABUSE,WORKPLACE_THEFT,FINANCIAL_MISCONDUCT,BRIBERY_CORRUPTION,CONFLICT_OF_INTEREST,PROCUREMENT_IRREGULARITIES,FAVORITISM,PUBLIC_SERVICE_FAILURE,LAW_ENFORCEMENT_ABUSE,JUDICIAL_MISCONDUCT,LAND_ADMIN_ISSUES,ACADEMIC_MISCONDUCT,EDUCATIONAL_ABUSE,ADMISSIONS_IRREGULARITIES,MEDICAL_MALPRACTICE,PATIENT_ABUSE,HEALTHCARE_FRAUD,DRUG_MISUSE,ENVIRONMENTAL_DAMAGE,WILDLIFE_CRIME,ILLEGAL_CONSTRUCTION,FALSE_ADVERTISING,PRODUCT_SAFETY,PRICE_GOUGING,DATA_PRIVACY_VIOLATION,CYBERCRIME,ONLINE_HARASSMENT,CHILD_EXPLOITATION,ILLEGAL_CONTENT,UNSAFE_BUILDINGS,ROAD_SAFETY_ISSUES,UTILITY_PROBLEMS,HUMAN_TRAFFICKING,FORCED_LABOR,DOMESTIC_ABUSE,MINORITY_RIGHTS_VIOLATION,ANIMAL_CRUELTY,NOISE_POLLUTION,VANDALISM,GENERAL_MISCONDUCT,OTHER] on the enum `Category` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Category_new" AS ENUM ('NGACIMI_NE_VENDIN_E_PUNES', 'DISKRIMIMI_NE_VENDIN_E_PUNES', 'SIGURIA_NE_VENDIN_E_PUNES', 'ABUZIMI_NE_VENDIN_E_PUNES', 'VEDIA_E_PASURISE_NE_VENDIN_E_PUNES', 'KEQPERDORIMI_FINANCIAR', 'RYSHFETI_KORRUPSIONI', 'KONFLIKTI_I_INTERESAVE', 'CENIME_NE_PROKURIM', 'FAVORIZIMI', 'DESHTIMI_I_SHERBIMEVE_PUBLIKE', 'ABUZIMI_NE_APARATIN_E_RENDIT', 'KEQPERDORIMI_I_DETYRAVE_GJYQESORE', 'PROBLEME_NE_ADMINISTRIMIN_E_TOKEN', 'KEQPERDORIMI_AKADEMIK', 'ABUZIMI_NE_ARSIM', 'CENIME_NE_PROCESIN_E_PRANIMEVE', 'GABIM_MJEKESOR', 'ABUZIMI_NDAJ_PACIENTEVE', 'MASHTRIME_NE_KUJDESIN_SHENDETESOR', 'KEQPERDORIMI_I_BILEVE', 'DEMTIMI_I_AMBIENTIT', 'KRIMET_NDAJ_JETESES_SEGERVE', 'NDERTIMI_I_PALIGJSHEM', 'REKLAMIM_I_RREJSHEM', 'SIGURIA_E_PRODUKTEVE', 'SHITJE_ME_CMIME_TEPER_TE_LARTA', 'SHKELJE_E_PRIVATESISE_SE_TE_DHENAVE', 'KRIMET_KIBERNETIKE', 'NGACIMI_ONLINE', 'EKSPLOATIMI_I_FEMIJEVE', 'PERMBATJE_E_PALIGJSHME', 'NDERTESA_TE_PASIGURTA', 'PROBLEME_ME_SIGURINE_RRUGORE', 'PROBLEME_ME_SHERBIMET_KOMMUNALE', 'TRAFIKIMI_I_QENIEVE_NJEREZORE', 'PUNE_E_DETYRUAR', 'DHUNA_NE_FAMILJE', 'SHKELJE_E_TE_DREJTAVE_TE_PAKICAVE', 'MIZORIA_NDAJ_KAFSHEVE', 'NDOTJA_ZANORE', 'VANDALIZEM', 'KEQPERDORIM_I_PERGJITHSHEM', 'TJETER');
ALTER TABLE "Complaint" ALTER COLUMN "category" TYPE "Category_new" USING ("category"::text::"Category_new");
ALTER TYPE "Category" RENAME TO "Category_old";
ALTER TYPE "Category_new" RENAME TO "Category";
DROP TYPE "Category_old";
COMMIT;
