/*
  Warnings:

  - You are about to drop the column `acceptedRequest` on the `Companies` table. All the data in the column will be lost.

*/
-- CreateEnum
CREATE TYPE "Category" AS ENUM ('WORKPLACE_HARASSMENT', 'WORKPLACE_DISCRIMINATION', 'WORKPLACE_SAFETY', 'WORKPLACE_ABUSE', 'WORKPLACE_THEFT', 'FINANCIAL_MISCONDUCT', 'BRIBERY_CORRUPTION', 'CONFLICT_OF_INTEREST', 'PROCUREMENT_IRREGULARITIES', 'FAVORITISM', 'PUBLIC_SERVICE_FAILURE', 'LAW_ENFORCEMENT_ABUSE', 'JUDICIAL_MISCONDUCT', 'LAND_ADMIN_ISSUES', 'ACADEMIC_MISCONDUCT', 'EDUCATIONAL_ABUSE', 'ADMISSIONS_IRREGULARITIES', 'MEDICAL_MALPRACTICE', 'PATIENT_ABUSE', 'HEALTHCARE_FRAUD', 'DRUG_MISUSE', 'ENVIRONMENTAL_DAMAGE', 'WILDLIFE_CRIME', 'ILLEGAL_CONSTRUCTION', 'FALSE_ADVERTISING', 'PRODUCT_SAFETY', 'PRICE_GOUGING', 'DATA_PRIVACY_VIOLATION', 'CYBERCRIME', 'ONLINE_HARASSMENT', 'CHILD_EXPLOITATION', 'ILLEGAL_CONTENT', 'UNSAFE_BUILDINGS', 'ROAD_SAFETY_ISSUES', 'UTILITY_PROBLEMS', 'HUMAN_TRAFFICKING', 'FORCED_LABOR', 'DOMESTIC_ABUSE', 'MINORITY_RIGHTS_VIOLATION', 'ANIMAL_CRUELTY', 'NOISE_POLLUTION', 'VANDALISM', 'GENERAL_MISCONDUCT', 'OTHER');

-- CreateEnum
CREATE TYPE "ComplaintStatus" AS ENUM ('PENDING', 'ACCEPTED');

-- AlterTable
ALTER TABLE "Companies" DROP COLUMN "acceptedRequest",
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE "Complaint" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "status" "ComplaintStatus" NOT NULL DEFAULT 'PENDING',
    "category" "Category" NOT NULL,
    "attachments" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL,
    "updatedat" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Complaint_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Complaint" ADD CONSTRAINT "Complaint_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
